### ISSUE TITLE
`slog_scope` panics with nested `with_logger` and `scope`

### ISSUE THREAD

**Issue by yjh0502** [slog-rs/slog#147]
Here's example code

```rust
#[macro_use(o, kv)]
extern crate slog;
extern crate slog_scope;

fn main() {
    let logger = slog::Logger::root(slog::Discard, o!());
    let _scope_guard = slog_scope::set_global_logger(logger);

    slog_scope::with_logger(|logger| slog_scope::scope(logger, || ()))
}
```

output log
```
RUST_BACKTRACE=1 target/release/test
thread 'main' panicked at 'already borrowed: BorrowMutError', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:41
  10: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/libcore/result.rs:799
             at /checkout/src/libcore/cell.rs:749
             at /home/jihyun/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-scope-4.0.0/lib.rs:178
             at /checkout/src/libstd/thread/local.rs:365
             at /checkout/src/libstd/thread/local.rs:279
  11: slog_scope::ScopeGuard::new
             at /home/jihyun/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-scope-4.0.0/lib.rs:178
  12: slog_scope::scope
             at /home/jihyun/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-scope-4.0.0/lib.rs:241
  13: <std::thread::local::LocalKey<T>>::with
             at src/bin/test.rs:9
             at /home/jihyun/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-scope-4.0.0/lib.rs:215
             at /checkout/src/libstd/thread/local.rs:365
             at /checkout/src/libstd/thread/local.rs:279
  14: test::main
             at src/bin/test.rs:9
  15: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:96
  16: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:61
  17: __libc_start_main
  18: <unknown>
```

Both ![with_logger](https://docs.rs/slog-scope/4.0.0/slog_scope/fn.with_logger.html) and ![scope](https://docs.rs/slog-scope/4.0.0/slog_scope/fn.scope.html) documentation don't have any panic section. I believe the problem should be documented at least.

**Comment by yjh0502** [comment]
moved to https://github.com/slog-rs/scope/issues/2

**Comment by dpc** [comment]
Let's continue on main slog issue tracker. I don't like tracking many issues across many small repos.

**Comment by dpc** [comment]
This is kind of expected. Scopes are represented as thread local stack of loggers, and `with_logger` will keep that stack in a "borrowed" state for the time of `f` closure:

https://docs.rs/slog-scope/4.0.0/src/slog_scope/lib.rs.html#209

So you can't modify logging scopes during `with_scope`. 

This should be better documented. I don't think it can be prevented. Generally, you should use `with_logger` for as short as possible and return whatever you need.
