### ISSUE TITLE
slog_scope no logger set error

### ISSUE THREAD

**Issue by ufoscout** [slog-rs/slog#249]
I have a strange error when trying to use slog_scope in an actix_web 2.0 application.
Here my dependencies:
```toml
slog = "2.5.2"
slog-async = "2.3.0"
slog-scope = "4.3.0"
slog-stdlog = "4.0.0"
slog-term = "2.4.2"
```

This is the slog initialization code which is called at application startup:
```rust
    println!("start LOGGER");

    let decorator = slog_term::TermDecorator::new().stdout().force_color().build();
    let drain = slog_term::FullFormat::new(decorator).build().fuse();
    let drain = slog_async::Async::new(drain).build().fuse();
    let logger = slog::Logger::root(drain, slog_o!("version" => env!("CARGO_PKG_VERSION")));

    println!("LOGGER created");

    let _scope_guard = slog_scope::set_global_logger(logger);

    println!("set SCOPE");
    slog_stdlog::init()?;
    println!("LOGGER SETUP COMPLETE");

    info!("LOG - LOGGER CONFIGURED PROPERLY"); // <-- This is printed correcly
    println!("PRINTLN - LOGGER CONFIGURED PROPERLY");
```

The log "info!" macro in the above code works as expected, anyway, any attempt to log from other portions of the code fails with this error:
```
panicked at 'slog-scope: No logger set. Use `slog_scope::set_global_logger` or `slog_scope::scope`.
```

Is there any incompatibility between this crate and, maybe, tokio 0.2?

This is the full error stack printed at application startup:

```
start LOGGER
LOGGER created
set SCOPE
LOGGER SETUP COMPLETE
PRINTLN - LOGGER CONFIGURED PROPERLY
Dec 27 17:23:55.012 INFO LOG - LOGGER CONFIGURED PROPERLY, version: 0.1.0
thread 'actix-web' panicked at 'slog-scope: No logger set. Use `slog_scope::set_global_logger` or `slog_scope::scope`.', /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-scope-4.3.0/lib.rs:125:13
stack backtrace:
   0:     0x55ce3ac22fb4 - backtrace::backtrace::libunwind::trace::h65597d255cb1398b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x55ce3ac22fb4 - backtrace::backtrace::trace_unsynchronized::hd4f479d7150ec4a0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x55ce3ac22fb4 - std::sys_common::backtrace::_print_fmt::h015072984a2b172c
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x55ce3ac22fb4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6df05d3335f32194
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x55ce3ac4756c - core::fmt::write::h1f444f4312eb6c27
                               at src/libcore/fmt/mod.rs:1028
   5:     0x55ce3ac1de67 - std::io::Write::write_fmt::h8d147888220078ef
                               at src/libstd/io/mod.rs:1412
   6:     0x55ce3ac2550e - std::sys_common::backtrace::_print::h8a6df0fa81d6af62
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x55ce3ac2550e - std::sys_common::backtrace::print::h6f05b4733407e509
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x55ce3ac2550e - std::panicking::default_hook::{{closure}}::h0d0a23bd02315dd8
                               at src/libstd/panicking.rs:188
   9:     0x55ce3ac25201 - std::panicking::default_hook::h8d15a9aecb4efac6
                               at src/libstd/panicking.rs:205
  10:     0x55ce3ac25c0b - std::panicking::rust_panic_with_hook::hbe174577402a475d
                               at src/libstd/panicking.rs:464
  11:     0x55ce3abd17c3 - std::panicking::begin_panic::h4548b94db1c9e8cd
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:400
  12:     0x55ce3a3a66de - <slog_scope::NoGlobalLoggerSet as slog::Drain>::log::ha1a32b8d14554c34
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-scope-4.3.0/lib.rs:125
  13:     0x55ce3a39c9bf - <alloc::sync::Arc<D> as slog::Drain>::log::had1cb0ca27bad8a7
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.5.2/src/lib.rs:1689
  14:     0x55ce3a39c920 - slog::Logger<D>::log::hcbda222f2ce7d19d
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.5.2/src/lib.rs:1203
  15:     0x55ce3a39b1a7 - <slog_stdlog::Logger as log::Log>::log::{{closure}}::h2a14dd07c06a3966
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-stdlog-4.0.0/lib.rs:98
  16:     0x55ce3a39b499 - slog_scope::with_logger::{{closure}}::h1f3b396adb4ed024
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-scope-4.3.0/lib.rs:221
  17:     0x55ce3a39c3ef - std::thread::local::LocalKey<T>::try_with::h3104799207c37be8
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:262
  18:     0x55ce3a39c298 - std::thread::local::LocalKey<T>::with::hf6f3c5bf595dd114
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:239
  19:     0x55ce3a39b2a9 - slog_scope::with_logger::h881687b938f88975
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-scope-4.3.0/lib.rs:217
  20:     0x55ce3a39b12e - <slog_stdlog::Logger as log::Log>::log::h727037b26d5fc689
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-stdlog-4.0.0/lib.rs:98
  21:     0x55ce3ac10602 - log::__private_api_log::hc3558786512b4923
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.4.8/src/lib.rs:1393
  22:     0x55ce39e6148e - slmd::main::{{closure}}::{{closure}}::h64bc089ed4466e6f
                               at slmd/src/main.rs:29
  23:     0x55ce39cfd550 - actix_threadpool::run::{{closure}}::{{closure}}::h5653b63f0bd66b54
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-threadpool-0.3.1/src/lib.rs:63
  24:     0x55ce39cfd656 - <F as threadpool::FnBox>::call_box::h3da86319f04ad3cc
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/threadpool-1.7.1/src/lib.rs:95
  25:     0x55ce3a9bd778 - threadpool::spawn_in_pool::{{closure}}::h0d5607060f03f2db
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/threadpool-1.7.1/src/lib.rs:767
  26:     0x55ce3a9a9363 - std::sys_common::backtrace::__rust_begin_short_backtrace::h73dde6d4d6c4d22f
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/sys_common/backtrace.rs:129
  27:     0x55ce3a9a9cdf - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::ha4c8fd2c32a7aa54
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/mod.rs:469
  28:     0x55ce3a9aece2 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hea24a4ade60d46ff
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panic.rs:317
  29:     0x55ce3a9afa69 - std::panicking::try::do_call::hdc50cc9b18ed030d
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:287
  30:     0x55ce3ac2a99a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  31:     0x55ce3a9af901 - std::panicking::try::h97b10a49d79977a1
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:265
  32:     0x55ce3a9af874 - std::panic::catch_unwind::h4ae123c591941504
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panic.rs:396
  33:     0x55ce3a9a9aea - std::thread::Builder::spawn_unchecked::{{closure}}::haeb7269c66edca46
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/mod.rs:468
  34:     0x55ce3a9ace64 - core::ops::function::FnOnce::call_once{{vtable.shim}}::ha9f8f8b022cd66ff
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/ops/function.rs:227
  35:     0x55ce3ac173df - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h3534c64212330b0c
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/boxed.rs:942
  36:     0x55ce3ac29ab0 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h338c10574a337ece
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/boxed.rs:942
  37:     0x55ce3ac29ab0 - std::sys_common::thread::start_thread::h761ac6d57710d65d
                               at src/libstd/sys_common/thread.rs:13
  38:     0x55ce3ac29ab0 - std::sys::unix::thread::Thread::new::thread_start::h61c012ef60f933c0
                               at src/libstd/sys/unix/thread.rs:79
  39:     0x7f8414ad26db - start_thread
  40:     0x7f84145e388f - __clone
  41:                0x0 - <unknown>
thread 'main' panicked at 'Should initialize the SMLD data: Canceled', src/libcore/result.rs:1165:5
stack backtrace:
   0:     0x55ce3ac22fb4 - backtrace::backtrace::libunwind::trace::h65597d255cb1398b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x55ce3ac22fb4 - backtrace::backtrace::trace_unsynchronized::hd4f479d7150ec4a0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x55ce3ac22fb4 - std::sys_common::backtrace::_print_fmt::h015072984a2b172c
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x55ce3ac22fb4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6df05d3335f32194
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x55ce3ac4756c - core::fmt::write::h1f444f4312eb6c27
                               at src/libcore/fmt/mod.rs:1028
   5:     0x55ce3ac1de67 - std::io::Write::write_fmt::h8d147888220078ef
                               at src/libstd/io/mod.rs:1412
   6:     0x55ce3ac2550e - std::sys_common::backtrace::_print::h8a6df0fa81d6af62
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x55ce3ac2550e - std::sys_common::backtrace::print::h6f05b4733407e509
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x55ce3ac2550e - std::panicking::default_hook::{{closure}}::h0d0a23bd02315dd8
                               at src/libstd/panicking.rs:188
   9:     0x55ce3ac25201 - std::panicking::default_hook::h8d15a9aecb4efac6
                               at src/libstd/panicking.rs:205
  10:     0x55ce3ac25c0b - std::panicking::rust_panic_with_hook::hbe174577402a475d
                               at src/libstd/panicking.rs:464
  11:     0x55ce3ac257ae - std::panicking::continue_panic_fmt::h4d855dad868accf3
                               at src/libstd/panicking.rs:373
  12:     0x55ce3ac25696 - rust_begin_unwind
                               at src/libstd/panicking.rs:302
  13:     0x55ce3ac4312e - core::panicking::panic_fmt::hdeb7979ab6591473
                               at src/libcore/panicking.rs:139
  14:     0x55ce3ac43227 - core::result::unwrap_failed::h054dd680e6fcd38b
                               at src/libcore/result.rs:1165
  15:     0x55ce39d14489 - core::result::Result<T,E>::expect::he4940a62769f634e
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/result.rs:960
  16:     0x55ce39e620e0 - slmd::main::{{closure}}::ha4ccc67142f45f7d
                               at slmd/src/main.rs:17
  17:     0x55ce39cc1772 - <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}::h7e9e6cde4224d83a
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:43
  18:     0x55ce39cc041b - std::future::set_task_context::h67aa98b9dcf0bc21
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:79
  19:     0x55ce39cc105a - <std::future::GenFuture<T> as core::future::future::Future>::poll::hacbdb41ffbea5b29
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:43
  20:     0x55ce39e61097 - <tokio::task::local::LocalFuture<F> as core::future::future::Future>::poll::h48b1f80285e4042f
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/task/local.rs:307
  21:     0x55ce39d304f2 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::h803e53d50580144f
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/basic_scheduler.rs:139
  22:     0x55ce39e4a0b3 - tokio::runtime::global::with_state::{{closure}}::hd8fe75410cb2c8d6
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/global.rs:100
  23:     0x55ce39d7d8c7 - std::thread::local::LocalKey<T>::try_with::he63cd0cc7e1a5a47
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:262
  24:     0x55ce39d7b5df - std::thread::local::LocalKey<T>::with::hb59b74615d690819
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:239
  25:     0x55ce39e49d8a - tokio::runtime::global::with_state::h8e16a5382bac2c3a
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/global.rs:83
  26:     0x55ce39e4a1f1 - tokio::runtime::global::with_basic_scheduler::hefebb3d09b832872
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/global.rs:62
  27:     0x55ce39d3024f - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::h8bf55886395f52f7
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/basic_scheduler.rs:122
  28:     0x55ce39c901e6 - tokio::runtime::Runtime::block_on::{{closure}}::h13c76faf5cdbc9d6
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/mod.rs:419
  29:     0x55ce39e49f37 - tokio::runtime::global::with_state::{{closure}}::h989f252537285210
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/global.rs:100
  30:     0x55ce39d7bdc1 - std::thread::local::LocalKey<T>::try_with::h3aabb79aa13372a4
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:262
  31:     0x55ce39d7aee4 - std::thread::local::LocalKey<T>::with::h2b9be22efac6b347
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:239
  32:     0x55ce39e49e05 - tokio::runtime::global::with_state::hab44b287ef4680e4
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/global.rs:83
  33:     0x55ce39e4a192 - tokio::runtime::global::with_basic_scheduler::hbf8e6252a896ba65
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/global.rs:62
  34:     0x55ce39d306a2 - tokio::runtime::basic_scheduler::Spawner::enter::hb2425ef5fe9601f2
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/basic_scheduler.rs:174
  35:     0x55ce39c63bc0 - tokio::runtime::spawner::Spawner::enter::hc204ed33dde353b6
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/spawner.rs:30
  36:     0x55ce39d30915 - tokio::runtime::handle::Handle::enter::{{closure}}::{{closure}}::h3908b7142e29a2bc
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/handle.rs:36
  37:     0x55ce39de90b5 - tokio::time::clock::Clock::enter::h9dfb5d66d867fa43
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/time/clock.rs:30
  38:     0x55ce39d2e176 - tokio::runtime::time::variant::with_default::h1557f7680158b084
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/time.rs:43
  39:     0x55ce39d30835 - tokio::runtime::handle::Handle::enter::{{closure}}::hb1f1d4a39ae7e63f
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/handle.rs:36
  40:     0x55ce39d4a655 - tokio::runtime::blocking::BlockingPool::enter::h991103410f115b93
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/blocking/mod.rs:63
  41:     0x55ce39d30755 - tokio::runtime::handle::Handle::enter::hc3b70df98da31427
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/handle.rs:33
  42:     0x55ce39c900e6 - tokio::runtime::Runtime::block_on::h081857bda4e420ef
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/mod.rs:416
  43:     0x55ce39e60d49 - tokio::task::local::LocalSet::block_on::{{closure}}::h47c2335425a8f712
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/task/local.rs:288
  44:     0x55ce39e60eca - tokio::task::local::Scheduler::with::{{closure}}::hea51013a6649b27b
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/task/local.rs:381
  45:     0x55ce39d7b921 - std::thread::local::LocalKey<T>::try_with::h0bb1cc0bc56e48a7
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:262
  46:     0x55ce39d7b564 - std::thread::local::LocalKey<T>::with::hb216f7872ce8cb0f
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:239
  47:     0x55ce39e60db8 - tokio::task::local::Scheduler::with::h2b4c2bd5f99a80ba
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/task/local.rs:377
  48:     0x55ce39e60c2b - tokio::task::local::LocalSet::block_on::h673dd7992cc07eaa
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/task/local.rs:287
  49:     0x55ce39d7a7da - actix_rt::runtime::Runtime::block_on::hef88d4bad5b3ef66
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.0.0/src/runtime.rs:89
  50:     0x55ce39d3b6ee - actix_rt::builder::SystemRunner::block_on::hebbd3feb165eb627
                               at /home/ufo/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.0.0/src/builder.rs:187
  51:     0x55ce39d7938b - slmd::main::h59e616b3de988655
                               at slmd/src/main.rs:15
  52:     0x55ce39ce4085 - std::rt::lang_start::{{closure}}::hc303af40d8578c55
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  53:     0x55ce3ac25633 - std::rt::lang_start_internal::{{closure}}::h6ea535ec5c50fc3e
                               at src/libstd/rt.rs:48
  54:     0x55ce3ac25633 - std::panicking::try::do_call::h631c6408dfccc6f5
                               at src/libstd/panicking.rs:287
  55:     0x55ce3ac2a99a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  56:     0x55ce3ac260ed - std::panicking::try::hab539b2d1255d635
                               at src/libstd/panicking.rs:265
  57:     0x55ce3ac260ed - std::panic::catch_unwind::hd5e0a26424bd7f34
                               at src/libstd/panic.rs:396
  58:     0x55ce3ac260ed - std::rt::lang_start_internal::h3bdc4c7d98181bf9
                               at src/libstd/rt.rs:47
  59:     0x55ce39ce4059 - std::rt::lang_start::h6c7c61bd7e7e01d9
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  60:     0x55ce39d793fa - main
  61:     0x7f84144e3b97 - __libc_start_main
  62:     0x55ce39c5f89a - _start
  63:                0x0 - <unknown>
Panic in Arbiter thread.

```

**Comment by dpc** [comment]
`_scope_guard` is being dropped and you did not call https://docs.rs/slog-scope/4.3.0/slog_scope/struct.GlobalLoggerGuard.html#method.cancel_reset ? Please reopen if that's not the case.

**Comment by ufoscout** [comment]
@dpc 
thanks, indeed, it solved my issue. Anyway, is this documented somewhere? I wasn't able to find any reference to it
