### ISSUE TITLE
Segfault with recursive calls

### ISSUE THREAD

**Issue by nazar-pc** [slog-rs/slog#263]
I have an app which when reduced does a bunch of iterations that look something like this:
```rust
fn call_with_thread(logger: slog::Logger) {
    std::thread::spawn(move || {
        call_no_thread(logger);
    });
}

fn call_no_thread(logger: slog::Logger) {
    let logger = logger.new(slog::o!(
        "key" => "value",
    ));
    slog::debug!(logger, "Hello");
    call_with_thread(logger);
}

call_with_thread(logger.clone());
```

Logger was initialized like this:
```rust
let drain = Json::new(io::stderr())
    .add_default_keys()
    .set_pretty(cfg!(debug_assertions))
    .build()
    .filter_level(config.log_level);
let safe_drain = Mutex::new(drain).map(slog::Fuse);
let values = o!("version" => VERSION);
let logger = Logger::root(safe_drain, values);
```

This is a contrived example, but what worried me is that I was getting segfault after some (big) number of iterations (with growing log output size), which is something that I do not expect from Rust code.

I'm not 100% sure this is slog's fault specifically, but it seems so, hopefully someone more familiar can take a look at this.

This is a backtrace from segfault:
<details>

```
#0  core::slice::<impl [T]>::len (self=...) at /rustc/664fcd3f046e2a6824602da0fad81e3e2bb0d409/src/libcore/slice/mod.rs:73
#1  0x000055f06c951506 in core::str::<impl str>::len (self=...) at /rustc/664fcd3f046e2a6824602da0fad81e3e2bb0d409/src/libcore/str/mod.rs:2250
#2  0x000055f06c94235b in core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::RangeFrom<usize>>::get_unchecked (self=..., slice=...) at /rustc/664fcd3f046e2a6824602da0fad81e3e2bb0d409/src/libcore/str/mod.rs:2040
#3  0x000055f06c942412 in core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::RangeFrom<usize>>::get (self=..., slice=...) at /rustc/664fcd3f046e2a6824602da0fad81e3e2bb0d409/src/libcore/str/mod.rs:2023
#4  0x000055f06c9424b4 in core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::RangeFrom<usize>>::index (self=..., slice=...) at /rustc/664fcd3f046e2a6824602da0fad81e3e2bb0d409/src/libcore/str/mod.rs:2052
#5  0x000055f06c908632 in core::str::traits::<impl core::ops::index::Index<I> for str>::index (self=..., index=...) at /rustc/664fcd3f046e2a6824602da0fad81e3e2bb0d409/src/libcore/str/mod.rs:1780
#6  0x000055f06c417ec3 in serde_json::ser::format_escaped_str_contents (writer=0x7ff9e9ff70c8, formatter=0x7ff9e9ff70d0, value=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.53/src/ser.rs:2110
#7  0x000055f06c417457 in serde_json::ser::format_escaped_str (writer=0x7ff9e9ff70c8, formatter=0x7ff9e9ff70d0, value=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.53/src/ser.rs:2075
#8  0x000055f06c422c1c in <&mut serde_json::ser::Serializer<W,F> as serde::ser::Serializer>::serialize_str (self=0x7ff9e9ff70c8, value=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.53/src/ser.rs:220
#9  0x000055f06c421a28 in <serde_json::ser::MapKeySerializer<W,F> as serde::ser::Serializer>::serialize_str (self=..., value=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.53/src/ser.rs:872
#10 0x000055f06c21c792 in serde::ser::impls::<impl serde::ser::Serialize for str>::serialize (self=..., serializer=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.110/src/ser/impls.rs:49
#11 0x000055f06c41d784 in <serde_json::ser::Compound<W,F> as serde::ser::SerializeMap>::serialize_key (self=0x7ff9e9ff6e08, key=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.53/src/ser.rs:693
#12 0x000055f06c41d277 in serde::ser::SerializeMap::serialize_entry (self=0x7ff9e9ff6e08, key=..., value=0x7ff9e97fc768) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.110/src/ser/mod.rs:1822
#13 0x000055f06c32f0ef in <slog_json::SerdeSerializer<S> as slog::Serializer>::emit_str (self=0x7ff9e9ff6e08, key=..., val=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-json-2.3.0/lib.rs:75
#14 0x000055f06cca5d26 in <alloc::string::String as slog::Value>::serialize (self=0x7ff9d8319580, _record=0x7ff9e9ff7f00, key=..., serializer=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.5.2/src/lib.rs:2859
#15 0x000055f06c285563 in <slog::SingleKV<V> as slog::KV>::serialize (self=0x7ff9d8319570, record=0x7ff9e9ff7f00, serializer=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.5.2/src/lib.rs:3206
#16 0x000055f06c282384 in <(T,R) as slog::KV>::serialize (self=0x7ff9d8319570, record=0x7ff9e9ff7f00, serializer=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.5.2/src/lib.rs:3226
#17 0x000055f06c282a6d in <(T,R) as slog::KV>::serialize (self=0x7ff9d8319558, record=0x7ff9e9ff7f00, serializer=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.5.2/src/lib.rs:3227
#18 0x000055f06c28251d in <(T,R) as slog::KV>::serialize (self=0x7ff9d8319540, record=0x7ff9e9ff7f00, serializer=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.5.2/src/lib.rs:3227
#19 0x000055f06c28284d in <(T,R) as slog::KV>::serialize (self=0x7ff9d8319528, record=0x7ff9e9ff7f00, serializer=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.5.2/src/lib.rs:3227
#20 0x000055f06c2821ed in <(T,R) as slog::KV>::serialize (self=0x7ff9d8319510, record=0x7ff9e9ff7f00, serializer=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.5.2/src/lib.rs:3227
#21 0x000055f06c2868c1 in <slog::OwnedKVListNode<T> as slog::KV>::serialize (self=0x7ff9d8319500, record=0x7ff9e9ff7f00, serializer=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.5.2/src/lib.rs:3350
#22 0x000055f06cca8126 in <alloc::sync::Arc<T> as slog::KV>::serialize (self=0x7ff9d8319790, record=0x7ff9e9ff7f00, serializer=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.5.2/src/lib.rs:3253
#23 0x000055f06c286948 in <slog::OwnedKVListNode<T> as slog::KV>::serialize (self=0x7ff9d8319790, record=0x7ff9e9ff7f00, serializer=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.5.2/src/lib.rs:3351
#24 0x000055f06cca8126 in <alloc::sync::Arc<T> as slog::KV>::serialize (self=0x7ff9d8319a20, record=0x7ff9e9ff7f00, serializer=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.5.2/src/lib.rs:3253
#25 0x000055f06c286948 in <slog::OwnedKVListNode<T> as slog::KV>::serialize (self=0x7ff9d8319a20, record=0x7ff9e9ff7f00, serializer=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.5.2/src/lib.rs:3351
#26 0x000055f06cca8126 in <alloc::sync::Arc<T> as slog::KV>::serialize (self=0x7ff9d8319cb0, record=0x7ff9e9ff7f00, serializer=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.5.2/src/lib.rs:3253
#27 0x000055f06c286948 in <slog::OwnedKVListNode<T> as slog::KV>::serialize (self=0x7ff9d8319cb0, record=0x7ff9e9ff7f00, serializer=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.5.2/src/lib.rs:3351
#28 0x000055f06cca8126 in <alloc::sync::Arc<T> as slog::KV>::serialize (self=0x7ff9d8319f40, record=0x7ff9e9ff7f00, serializer=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.5.2/src/lib.rs:3253
#29 0x000055f06c286948 in <slog::OwnedKVListNode<T> as slog::KV>::serialize (self=0x7ff9d8319f40, record=0x7ff9e9ff7f00, serializer=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.5.2/src/lib.rs:3351
#30 0x000055f06cca8126 in <alloc::sync::Arc<T> as slog::KV>::serialize (self=0x7ff9d831a1d0, record=0x7ff9e9ff7f00, serializer=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.5.2/src/lib.rs:3253
#31 0x000055f06c286948 in <slog::OwnedKVListNode<T> as slog::KV>::serialize (self=0x7ff9d831a1d0, record=0x7ff9e9ff7f00, serializer=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.5.2/src/lib.rs:3351
#32 0x000055f06cca8126 in <alloc::sync::Arc<T> as slog::KV>::serialize (self=0x7ff9d831a460, record=0x7ff9e9ff7f00, serializer=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.5.2/src/lib.rs:3253
#33 0x000055f06c286948 in <slog::OwnedKVListNode<T> as slog::KV>::serialize (self=0x7ff9d831a460, record=0x7ff9e9ff7f00, serializer=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.5.2/src/lib.rs:3351
#34 0x000055f06cca8126 in <alloc::sync::Arc<T> as slog::KV>::serialize (self=0x7ff9d831a6f0, record=0x7ff9e9ff7f00, serializer=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.5.2/src/lib.rs:3253
#35 0x000055f06c286948 in <slog::OwnedKVListNode<T> as slog::KV>::serialize (self=0x7ff9d831a6f0, record=0x7ff9e9ff7f00, serializer=...) at /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.5.2/src/lib.rs:3351
...
```

</details>

**Comment by dpc** [comment]
AFAIK, it's possible to segfault in Rust. What's important is that you segfaulted in a safe way, hitting stack guard or something like this. Can't really do much about it, I guess. Use https://users.rust-lang.org/ for general Rust questions.
