### ISSUE TITLE
Panic during file rotation

### ISSUE THREAD

**Issue by crusty-dave** [slog-rs/slog#283]
On Windows, I was attempting to monitor my log via the following command:
`powershell Get-Content C:\Users\%USERNAME%\AppData\Local\Temp\1\server-debug.log -wait
`

I received the following panic:

```
thread '<unnamed>' panicked at 'slog::Fuse Drain: Os { code: 32, kind: Other, message: "The process cannot access the file because it is being used by another process." }', C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\slog-2.7.0\src\lib.rs:1944:33
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:475
   1: std::panicking::begin_panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:429
   2: slog::{{impl}}::log::{{closure}}<slog_term::FullFormat<slog_term::PlainDecorator<sloggers::file::FileAppender>>>
             at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\slog-2.7.0\src\lib.rs:1944
   3: core::result::Result<tuple<>, std::io::error::Error>::unwrap_or_else<tuple<>,std::io::error::Error,closure-0>
             at C:\Users\user\.rustup\toolchains\1.47.0-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\result.rs:825
   4: slog::{{impl}}::log<slog_term::FullFormat<slog_term::PlainDecorator<sloggers::file::FileAppender>>>
             at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\slog-2.7.0\src\lib.rs:1942
   5: slog_async::AsyncRecord::log_to<slog::Fuse<slog_term::FullFormat<slog_term::PlainDecorator<sloggers::file::FileAppender>>>>
             at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\slog-async-2.6.0\lib.rs:496
   6: slog_async::{{impl}}::spawn_thread::{{closure}}<slog::Fuse<slog_term::FullFormat<slog_term::PlainDecorator<sloggers::file::FileAppender>>>>
             at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\slog-async-2.6.0\lib.rs:288
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```
It turns out that the PowerShell command keeps the file open, which apparently led to the panic.

I believe the panic is triggered by an extremely large log entry that is being output by PowerShell when slog decides that it needs to rotate the file.

Can we add some sort of builder option to avoid the panic?  I am not sure of the correct way to handle this, but panic is a hammer that I would prefer not to have happen.  Can I somehow override Drain while still using sloggers?

I still need to see if I can avoid it by suppressing those large log entries.

```
impl<D: Drain> Drain for Fuse<D>
where
    D::Err: fmt::Debug,
{
    type Ok = ();
    type Err = Never;
    fn log(
        &self,
        record: &Record,
        logger_values: &OwnedKVList,
    ) -> result::Result<Self::Ok, Never> {
        let _ = self.0
            .log(record, logger_values)
            .unwrap_or_else(|e| panic!("slog::Fuse Drain: {:?}", e));
        Ok(())
    }
    #[inline]
    fn is_enabled(&self, level: Level) -> bool {
        self.0.is_enabled(level)
    }
}
```

Here is how I configured the log:

```
        let logger = if is_service || log_config.log_to_file {
            match FileLoggerBuilder::new(&self.log_path)
                .timezone(TimeZone::Utc)
                .source_location(SourceLocation::LocalFileAndLine)
                .rotate_size(log_config.max_size_bytes())
                .rotate_keep(log_config.rotate_keep)
                .level(severity)
                .channel_size(4096)
                .overflow_strategy(OverflowStrategy::DropAndReport)
                .build()
            {
                Ok(file_logger) => {
                    file_logger
                },
                Err(e) => {
                    return Err(format!("{:?}", e));
                }
            }
        } else {
            let mut stderr_builder = TerminalLoggerBuilder::new();
            stderr_builder.level(severity);
            stderr_builder.destination(Destination::Stdout);

            match stderr_builder.build() {
                Ok(logger) => {
                    logger
                }
                Err(e) => {
                    return Err(format!("{:?}", e));
                }
            }
        };
        if let Err(e) = sloggers::set_stdlog_logger(logger.clone()) {
            return Err(format!("failed to set logger, {:?}", e));
        }
        let logger_guard = slog_scope::set_global_logger(logger.clone());
```

In this case I am using FileLoggerBuilder.

This is easily reproducible on Windows using the PowerShell command.

[update.1] it seems to only be an issue when the log entry being displayed by PowerShell exceeds the rotate_size, so this is less urgent, but probably still worth noting.

[update.2] I did hit the panic in a case where I was writing a lot of log messages with the PowerShell log monitoring running, so this would seem to be problematic after all.

Thanks in advance,
-Dave

**Comment by dpc** [comment]
`slog` and `slog-term` do not implement file rotation. You probably want to open the issue in `sloggers` repo, I'm not sure if `slogges` maintainer checks issues here.

**Comment by crusty-dave** [comment]
Opened a new issue in sloggers:
https://github.com/sile/sloggers/issues/43
